### ISSUE TITLE
Training time and gpu memory

### ISSUE THREAD

**Issue by niecongchong** [jpjuvo/camelyon17-multilevel#1]
Hello, I have just started my research on Camelyon17, and I would like to ask you about the **GPU memory and time** you need to train the whole data set. 
Thank you very much!

**Comment by jpjuvo** [comment]
GPU memory requirements depend on three things; chosen model, input image size, and the size of your training batch. 
For instance, ResNet50 with a batch size of 4 and an input size of 256x256 allocates ~3-4 GB of GPU memory (could be less. This is just from my memory). I would say that a GPU with 4 GB of memory is sufficient but the more you have, the less you have to worry about model and batch size. 

If you run into CUDA out of memory errors during training, you can decrease the batch size, choose a smaller model, or resize images smaller until the memory doesn't run out.

Training time depends on the data set size, model size (number of trainable parameters), and your GPU.

For reference, I split the Camelyon17 WSIs into smaller 256x256 tiles and used roughly 70K of those in training. It took 30 minutes to train one epoch with NVIDIA V100 (32 GB) GPU and SE-ResNext-101, and it didn't take many epochs to converge.
